/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import com.mycompany.metodosnum.MetodosNum;
import java.awt.Color;
import javax.swing.BorderFactory;
/**
 *
 * @author hfyh
 */
public class ObtenerFuncion extends javax.swing.JFrame {

    /**
     * Creates new form ObtenerFuncion
     */
    String funcion;
    private int metodo;
    
    public ObtenerFuncion() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public ObtenerFuncion(int metodo) {
        this.metodo = metodo;
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Selecionar función");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgObtenerFuncion = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        fieldFuncion = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listFunctions = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        lblError2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        bgObtenerFuncion.setBackground(new java.awt.Color(205, 245, 253));
        bgObtenerFuncion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 169, 255));

        jLabel1.setBackground(new java.awt.Color(58, 117, 220));
        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Escoge que deseas hacer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        bgObtenerFuncion.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 690, 60));

        jPanel2.setBackground(new java.awt.Color(160, 233, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ingresa la función:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 90, -1, -1));

        fieldFuncion.setBackground(new java.awt.Color(160, 233, 255));
        fieldFuncion.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        fieldFuncion.setForeground(new java.awt.Color(0, 0, 0));
        fieldFuncion.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.WHITE));
        fieldFuncion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldFuncionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldFuncionFocusLost(evt);
            }
        });
        jPanel2.add(fieldFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 111, 288, -1));

        jPanel4.setBackground(new java.awt.Color(0, 169, 255));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Escribir mi función");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 2, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Recuerda escribir en terminos de x");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 57, 294, -1));

        lblError.setFont(new java.awt.Font("Roboto Light", 2, 12)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 77, 43));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblError.setText("Error: esdfefsesfe");
        jPanel2.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 158, 300, 17));

        jButton1.setBackground(new java.awt.Color(0, 169, 255));
        jButton1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Elegir función");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 181, 107, 31));

        bgObtenerFuncion.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 300, 220));

        jPanel3.setBackground(new java.awt.Color(160, 233, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 169, 255));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Escoge una función");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(160, 233, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        listFunctions.setBackground(new java.awt.Color(137, 207, 243));
        listFunctions.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        listFunctions.setForeground(new java.awt.Color(0, 0, 0));
        listFunctions.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "2x^2 - 1", "2x + 3", "x^4 + 3x^3 - 2", "50x - 0.35e^(0.75x)" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listFunctions.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listFunctions.setToolTipText("Escoja una función");
        jScrollPane1.setViewportView(listFunctions);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 300, 80));

        jButton3.setBackground(new java.awt.Color(0, 169, 255));
        jButton3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Confirmar");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.setPreferredSize(new java.awt.Dimension(84, 31));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        lblError2.setFont(new java.awt.Font("Roboto Light", 2, 12)); // NOI18N
        lblError2.setForeground(new java.awt.Color(255, 77, 43));
        lblError2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblError2.setText("Error: esdfefsesfe");
        jPanel3.add(lblError2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 300, 17));

        bgObtenerFuncion.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 300, 220));

        jButton2.setBackground(new java.awt.Color(0, 169, 255));
        jButton2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Volver");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        bgObtenerFuncion.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 340, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgObtenerFuncion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgObtenerFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new MetodosNum().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void metodo(int op_metodo, String funcion){
        switch (op_metodo) {
            case 1:
                new MetodoBiseccion(funcion).setVisible(true);
                dispose();
                break;
            case 2:
                new MetodoSecante(funcion).setVisible(true);
                dispose();
                break;
            case 3:
                new MetodoNewton(funcion).setVisible(true);
                dispose();
                break;
            case 4:
                new MetodoPosicion(funcion).setVisible(true);
                dispose();
                break;
            default:
                throw new AssertionError();
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            if(!fieldFuncion.getText().isEmpty()){
                funcion = fieldFuncion.getText();
                lblError.setVisible(false);
                metodo(this.metodo, funcion);
            } else{
                lblError.setText("Error: Ingrese una función.");
                lblError.setVisible(true);
            }
        } catch (Exception e) {
            lblError.setText("Error: "+e.getMessage());
            lblError.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            if(listFunctions.getSelectedValue()!=null){
                funcion = listFunctions.getSelectedValue();
                lblError2.setVisible(false);
                metodo(this.metodo, funcion);
            } else{
                lblError2.setText("Error: Seleccione una función.");
                lblError2.setVisible(true);
            }
        } catch (Exception e) {
            lblError2.setText("Error: "+e.getMessage());
            lblError2.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        lblError.setVisible(false);
        lblError2.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void fieldFuncionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldFuncionFocusGained
        // TODO add your handling code here:
        fieldFuncion.setBackground(new Color(205,245,253));
        
    }//GEN-LAST:event_fieldFuncionFocusGained

    private void fieldFuncionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldFuncionFocusLost
        // TODO add your handling code here:
        fieldFuncion.setBackground(new Color(160,233,255));
    }//GEN-LAST:event_fieldFuncionFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ObtenerFuncion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ObtenerFuncion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ObtenerFuncion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ObtenerFuncion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ObtenerFuncion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgObtenerFuncion;
    private javax.swing.JTextField fieldFuncion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblError2;
    private javax.swing.JList<String> listFunctions;
    // End of variables declaration//GEN-END:variables
}
